name: Update submodules

on:
  schedule:
    - cron: '0 * * * *' # Every hour

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: UltraFeed/editorconfig
        ref: main
        submodules: 'recursive'

    - name: Update submodules
      run: |
        git submodule update --init --recursive
        git submodule foreach git pull origin master
